getcontext and setcontext functions added
Wenzel/xenctrl pull request #14
Opened 2020-07-17 14:29 UTC by arnabcs17b006

2020-07-26 18:48 UTC, Wenzel commented on Cargo.toml
> +xenvmevent-sys = { git = "https://github.com/Wenzel/xenvmevent-sys.git", optional = true }
@arnabcs17b006 remove the `optional =  true` here, otherwise this crate will be skipped from the compilation process ;)

2020-08-19 23:22 UTC, Wenzel requested changes
see my comments

2020-08-19 23:22 UTC, Wenzel commented on .vscode/settings.json
> +{
why did you committed this vscode file ?

2020-08-19 23:22 UTC, Wenzel commented on src/lib.rs
> +            println!("last OS error: {:?}", Error::last_os_error());
you should print an error message.
return and Error:
https://github.com/Wenzel/xenstore/blob/master/src/lib.rs#L38

2020-08-19 23:22 UTC, Wenzel commented on src/lib.rs
> +            println!("last OS error: {:?}", Error::last_os_error());
Same here

2020-08-19 23:22 UTC, Wenzel commented on src/lib.rs
> +            println!("last OS error: {:?}", Error::last_os_error());
same here

2020-08-19 23:22 UTC, Wenzel commented on src/lib.rs
> +/*fn ring_get_request(back_ring: &vm_event_back_ring, req_cons: u32) -> vm_event_request_t {
why is this code commented ?

2020-08-26 21:21 UTC, Wenzel requested changes

2020-08-26 21:21 UTC, Wenzel commented on src/lib.rs
> +        let mut max_gpfn = mem::MaybeUninit::<u64>::uninit();
why do you use maybeUninit here ?
just set it to 0 and pass the mutable pointer

2020-08-26 21:22 UTC, Wenzel commented on src/lib.rs
> +        let mut max_gpfn = mem::MaybeUninit::<u64>::uninit();
MaybeUninit is useful with structures where Default trait is not available.

2020-08-26 21:29 UTC, arnabcs17b006 commented
Actually this code was written by you. I just ignored the clippy check so
as to pass the build.
Should o change it?

On Thu, Aug 27, 2020, 02:52 Mathieu Tarral <notifications@github.com> wrote:

> *@Wenzel* commented on this pull request.
> ------------------------------
>
> In src/lib.rs
> <https://github.com/Wenzel/xenctrl/pull/14#discussion_r477597046>:
>
> >      pub fn domain_maximum_gpfn(&self, domid: u32) -> Result<u64> {
>          let xc = self.handle.as_ptr();
> +        #[allow(unused_assignments)]
> +        let mut max_gpfn = mem::MaybeUninit::<u64>::uninit();
>
> MaybeUninit is useful with structures where Default trait is not available.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Wenzel/xenctrl/pull/14#discussion_r477597046>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALGMDC4VTARZMLQWDZH3JULSCV4JFANCNFSM4O6LEOHA>
> .
>

2020-08-26 21:41 UTC, Wenzel commented
Funny.
I guess I learned some Rust in between !

it's okay, I'll test it, and merge if it works.

2020-08-26 21:59 UTC, arnabcs17b006 commented
🤣

On Thu, Aug 27, 2020, 03:11 Mathieu Tarral <notifications@github.com> wrote:

> Funny.
> I guess I learned some Rust in between !
>
> it's okay, I'll test it, and merge if it works.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Wenzel/xenctrl/pull/14#issuecomment-681138628>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALGMDC5IXALXWPLQ63X4S43SCV6P7ANCNFSM4O6LEOHA>
> .
>

2020-08-26 21:59 UTC, Wenzel commented on src/lib.rs
> +        unsafe {
Could you explain and add some comments on this code ?
thanks.

2020-12-16 22:21 UTC, closed without merging