Breakpoint
Wenzel/xenctrl pull request #18
Opened 2020-08-14 18:10 UTC by arnabcs17b006

2020-08-26 22:03 UTC, Wenzel requested changes

2020-08-26 22:03 UTC, Wenzel commented on .vscode/settings.json
> +{
we don't need your IDE files

2020-08-26 22:03 UTC, Wenzel commented on src/lib.rs
> +            println!("last OS error: {:?}", Error::last_os_error());
no println

2020-08-28 22:04 UTC, Wenzel commented
I don't get it either.
I looked at the generated bindings, and the `value` field is there
![Capture d’écran de 2020-08-29 00-02-28](https://user-images.githubusercontent.com/964610/91618658-3b218580-e98b-11ea-9530-67c62f0334a3.png)

2020-08-28 22:13 UTC, arnabcs17b006 commented
It also works fine locally..

On Sat, Aug 29, 2020, 03:34 Mathieu Tarral <notifications@github.com> wrote:

> I don't get it either.
> I looked at the generated bindings, and the value field is there
> [image: Capture d’écran de 2020-08-29 00-02-28]
> <https://user-images.githubusercontent.com/964610/91618658-3b218580-e98b-11ea-9530-67c62f0334a3.png>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Wenzel/xenctrl/pull/18#issuecomment-683166067>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALGMDC75KGI6RCQDER3LL43SDASYNANCNFSM4P7XS43Q>
> .
>

2020-08-28 22:20 UTC, Wenzel commented
When I look at my `vm_event.h` header, i have this:
![Capture d’écran de 2020-08-29 00-14-50](https://user-images.githubusercontent.com/964610/91619205-bfc0d380-e98c-11ea-857e-c83f6d57cf03.png)ù

So I suspect this is linked to the version of Xen you are using.
I have Xen 4.11

Looking at the Xen source code, this [commit](https://github.com/xen-project/xen/commit/b55f6c299d316b00f65b63137fde8c2524fb638a#diff-4f1f0664b6782533c6ae2d860fb6e27fR263) introduces the old MSR value and changed the fiekd, likely since Xen 4.11 rc1

2020-08-28 22:25 UTC, Wenzel commented
Also, about Ubuntu 16.04 failing on the CI, same thing
this [commit](https://github.com/xen-project/xen/commit/94db5dbb6c5f331dac35a8723a5d982ad17536d6) added the `insn_length` field, since Xen 4.8.0 rc1.

How should we handle backward compatibility with bindgen, since it generates the bindgen for the current headers only ?
cc @rageagainsthepc

2020-08-28 22:27 UTC, arnabcs17b006 commented
I thought the issue was with insn_len of vm_event_debug struct?

On Sat, Aug 29, 2020, 03:50 Mathieu Tarral <notifications@github.com> wrote:

> When I look at my vm_event.h header, i have this:
> [image: Capture d’écran de 2020-08-29 00-14-50]
> <https://user-images.githubusercontent.com/964610/91619205-bfc0d380-e98c-11ea-857e-c83f6d57cf03.png>
> ù
>
> So I suspect this is linked to the version of Xen you are using.
> I have Xen 4.11
>
> Looking at the Xen source code, this commit
> <https://github.com/xen-project/xen/commit/b55f6c299d316b00f65b63137fde8c2524fb638a#diff-4f1f0664b6782533c6ae2d860fb6e27fR263>
> introduces the old MSR value and changed the fiekd, likely since Xen 4.11
> rc1
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Wenzel/xenctrl/pull/18#issuecomment-683170816>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALGMDC5WOSTJXVJ57FPHE7TSDAUS7ANCNFSM4P7XS43Q>
> .
>

2020-08-28 22:27 UTC, Wenzel commented
It is, this is exactly what my last comment was saying.

2020-08-28 22:37 UTC, Wenzel commented
One solution: move to Xen 4.11 APIs, drop Ubuntu 16.04 compat ?

If you look at LibVMI, they define multiple `process_request_x` for each API version:
https://github.com/libvmi/libvmi/blob/master/libvmi/driver/xen/xen_events.c#L1384

2020-08-30 21:20 UTC, Wenzel commented
The solution I see here:
drop Xen 4.6 support (Ubuntu 16.04), and only use Xen 4.9 (Ubuntu 18.04) from now on.

2020-09-02 07:03 UTC, rageagainsthepc commented
We should also mention somewhere that we don't support Xen versions below 4.9.

2020-09-02 18:43 UTC, Wenzel commented
https://github.com/Wenzel/xenctrl/pull/26 has been merged.
Arnab you can rebase and the CI should go green.

2020-12-17 13:36 UTC, closed without merging